# Generated by Django 3.2 on 2021-07-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_suscriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptor',
            old_name='fechasus',
            new_name='fecha_suscripcion',
        ),
    ]
