# Generated by Django 3.2 on 2021-07-07 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_suscriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptor',
            name='fechasus',
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='fecha_suscripcion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
